# -*- coding: utf-8 -*-
"""
markdown_exporter.py - Xuất Content Brief ra file Markdown (.md).

Render Content Brief dict thành file .md với format "Show Your Work":
  PHẦN 1: Báo cáo Phân tích Dữ liệu Thực tế
  PHẦN 2: Content Brief (Dựa trên dữ liệu Phần 1)
"""

import logging
import os
import re
import unicodedata
from typing import Dict, Tuple

logger = logging.getLogger(__name__)


def export_to_markdown(brief: Dict, output_dir: str) -> Tuple[str, str, str]:
    """
    Xuất Content Brief thành file Markdown.

    Args:
        brief: Dict chứa toàn bộ Content Brief.
        output_dir: Thư mục đầu ra.

    Returns:
        Tuple[str, str, str]: (Đường dẫn tuyệt đối, Part 1 Markdown, Part 2 Markdown)
    """
    os.makedirs(output_dir, exist_ok=True)

    filename = _slugify(brief["topic"]) + ".md"
    filepath = os.path.join(output_dir, filename)

    content, part1_md, part2_md = _render_markdown(brief)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info("  → Đã xuất: %s", filepath)
    return os.path.abspath(filepath), part1_md, part2_md


# ──────────────────────────────────────────────
#  PRIVATE HELPERS
# ──────────────────────────────────────────────

def _slugify(text: str) -> str:
    """
    Chuyển đổi text tiếng Việt thành slug cho tên file.

    VD: "Thép tấm là gì" → "thep-tam-la-gi"
    """
    # Bảng chuyển đổi dấu tiếng Việt
    vietnamese_map = {
        'à': 'a', 'á': 'a', 'ả': 'a', 'ã': 'a', 'ạ': 'a',
        'ă': 'a', 'ằ': 'a', 'ắ': 'a', 'ẳ': 'a', 'ẵ': 'a', 'ặ': 'a',
        'â': 'a', 'ầ': 'a', 'ấ': 'a', 'ẩ': 'a', 'ẫ': 'a', 'ậ': 'a',
        'è': 'e', 'é': 'e', 'ẻ': 'e', 'ẽ': 'e', 'ẹ': 'e',
        'ê': 'e', 'ề': 'e', 'ế': 'e', 'ể': 'e', 'ễ': 'e', 'ệ': 'e',
        'ì': 'i', 'í': 'i', 'ỉ': 'i', 'ĩ': 'i', 'ị': 'i',
        'ò': 'o', 'ó': 'o', 'ỏ': 'o', 'õ': 'o', 'ọ': 'o',
        'ô': 'o', 'ồ': 'o', 'ố': 'o', 'ổ': 'o', 'ỗ': 'o', 'ộ': 'o',
        'ơ': 'o', 'ờ': 'o', 'ớ': 'o', 'ở': 'o', 'ỡ': 'o', 'ợ': 'o',
        'ù': 'u', 'ú': 'u', 'ủ': 'u', 'ũ': 'u', 'ụ': 'u',
        'ư': 'u', 'ừ': 'u', 'ứ': 'u', 'ử': 'u', 'ữ': 'u', 'ự': 'u',
        'ỳ': 'y', 'ý': 'y', 'ỷ': 'y', 'ỹ': 'y', 'ỵ': 'y',
        'đ': 'd',
    }

    text = text.lower().strip()

    # Thay thế ký tự tiếng Việt
    result = []
    for char in text:
        if char in vietnamese_map:
            result.append(vietnamese_map[char])
        else:
            result.append(char)
    text = "".join(result)

    # Chuẩn hóa Unicode
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")

    # Thay thế khoảng trắng và ký tự đặc biệt
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    text = text.strip("-")

    return text or "untitled"


def _render_markdown(brief: Dict) -> Tuple[str, str, str]:
    """
    Render toàn bộ Content Brief thành chuỗi Markdown.

    Cấu trúc "Show Your Work" (V7):
        PHẦN 1: ACTIONABLE CONTENT BRIEF
        PHẦN 2: METHODOLOGY & WRITING GUIDELINES
        PHẦN 3: DATA ANALYSIS (Reference)
        
    Returns:
        Tuple[str, str, str]: (full_content, part1_content, part2_content)
    """
    lines = []
    
    # ── HEADER ──
    lines.append(f"# BÁO CÁO PHÂN TÍCH & CONTENT BRIEF: {brief['topic']}")
    lines.append("")
    lines.append("> **Ngày tạo**: Auto-generated by Content Brief Generator")
    lines.append("")
    lines.append("---")
    lines.append("")

    has_serp = "serp_analysis" in brief
    has_competitor = "competitor_analysis" in brief

    # ══════════════════════════════════════════════════════════
    #  PHẦN 1: ACTIONABLE CONTENT BRIEF
    # ══════════════════════════════════════════════════════════
    lines.append("# PHẦN 1: ACTIONABLE CONTENT BRIEF")
    lines.append("")
    
    section_num = 1
    
    # ── 1.1 META INFORMATION ──
    lines.append(f"## {section_num}. Meta Information")
    lines.append("")
    lines.append("| Hạng mục | Nội dung |")
    lines.append("|---|---|")
    lines.append(f"| **Title Tag** | {brief.get('title_tag', '')} |")
    lines.append(f"| **Meta Description** | {brief.get('meta_description', '')} |")
    lines.append(f"| **Target Keyword** | {brief['topic']} |")
    lines.append(f"| **Central Entity** | {brief.get('central_entity', '')} |")
    lines.append("")
    section_num += 1

    # ── 1.2 SEMANTIC OUTLINE (DÀN Ý TREE) ──
    lines.append(f"## {section_num}. Semantic Outline")
    lines.append("")
    
    if has_serp and has_competitor:
        lines.append("> ✅ Outline từ dữ liệu thực tế (PAA + Competitor + Content Gaps)")
    else:
        lines.append("> ⚠️ Outline rule-based (không có SERP)")
    lines.append("")

    micro_data = brief.get("micro_briefing", [])
    heading_structure = brief.get("heading_structure", [])

    # Render clean tree: H1 → H2 → H3
    for h in heading_structure:
        level = h.get("level", "H2")
        text = h.get("text", "")
        if level == "H1":
            lines.append(f"**{text}**")
        elif level == "H2":
            role_icon = "🟢" if "[MAIN]" in text else "🟡"
            clean = text.replace("[MAIN] ", "").replace("[SUPP] ", "")
            role = "[MAIN]" if "[MAIN]" in text else "[SUPP]"
            lines.append(f"- {role_icon} **{role}** {clean}")
        elif level == "H3":
            lines.append(f"  - ↳ {text}")
        elif level == "H4":
            lines.append(f"    - ↳ {text}")
    lines.append("")
    
    # H3 ratio summary
    h2_count = sum(1 for h in heading_structure if h.get("level") == "H2")
    h3_count = sum(1 for h in heading_structure if h.get("level") == "H3")
    ratio_pct = round(h3_count / h2_count * 100) if h2_count else 0
    status_icon = "✅" if ratio_pct >= 50 else "⚠️"
    lines.append(f"> {status_icon} H3 Ratio: {h3_count} H3 / {h2_count} H2 = {ratio_pct}% (chuẩn ≥50%)")
    lines.append("")

    # ── Koray: H3 Micro-Briefing (each H3 gets its own micro-briefing) ──
    h3_list = [(h["text"], h.get("parent_h2", "")) for h in heading_structure if h.get("level") == "H3"]
    if h3_list:
        lines.append("> **🎯 H3 Micro-Briefing (Koray: Mỗi H3 có hướng dẫn riêng):**")
        lines.append("")
        for h3_text, parent_h2 in h3_list:
            clean_h3 = h3_text.replace("[MAIN] ", "").replace("[SUPP] ", "").replace("↳ ", "").strip()
            # Find micro_data for this H3's parent H2
            parent_clean = parent_h2.replace("[MAIN] ", "").replace("[SUPP] ", "").strip() if parent_h2 else ""
            # Get info_gain from parent H2 micro_briefing
            h3_hint = ""
            for micro in (micro_data or []):
                h2_name = micro.get("h2", "")
                h2_clean = h2_name.replace("[MAIN] ", "").replace("[SUPP] ", "").strip()
                if parent_clean and (parent_clean.lower() in h2_clean.lower() or h2_clean.lower() in parent_clean.lower()):
                    ig = micro.get("info_gain", "")
                    if ig:
                        # Extract H3 names if mentioned in info_gain
                        import re as _re2
                        h3_names = _re2.findall(r'(?:gồm:|bao gồm:)\s*([^.]+)', ig, _re2.IGNORECASE)
                        if h3_names:
                            h3_hint = h3_names[0].strip()
                    break
            lines.append(f"- **H3: {clean_h3}**")
            if h3_hint:
                hint_clean = h3_hint.split(",")[0].strip() if "," in h3_hint else h3_hint.strip()
                lines.append(f"  ↳ {hint_clean[:100]}{'...' if len(h3_hint) > 100 else ''}")
            else:
                lines.append(f"  ↳ Viết 80-150 từ. Bắt đầu bằng câu trả lời trực tiếp câu hỏi H3. Có số liệu kỹ thuật cụ thể.")
            lines.append("")
    section_num += 1

    # ── 1.3 KORAY COLUMNS (EAV + Macro Context + FS/PAA Map + Source Context) ──
    eav_block    = brief.get("eav_table", "") or brief.get("eav", "")
    macro_block   = brief.get("macro_context", "") or brief.get("macro_context_str", "")
    fspaa_block   = brief.get("fs_paa_map", "") or brief.get("fs_paa", "")
    src_ctx_block = brief.get("source_context_alignment", "") or ""

    has_koray = macro_block or eav_block or fspaa_block or src_ctx_block
    if has_koray:
        lines.append(f"## {section_num}. Bảng Phân Tích Koray")
        lines.append("")
        lines.append("> Nhung phan tich chuyen su thu 4 (Chi phi Toc thoi - Thu thuat Tot nhat): EAV Table, Macro Context, FS/PAA Map, Source Context Alignment.")
        lines.append("")

        if macro_block:
            lines.append("### D. Macro Context")
            lines.append("")
            for l in macro_block.strip().splitlines():
                if l.strip():
                    lines.append(l)
            lines.append("")

        if eav_block:
            lines.append("### E. EAV Table (Entity - Attribute - Value)")
            lines.append("")
            lines.append("> Bang EAV la THANH PHAN BAT BUOC — Neu khong co, Writer se khong biet cac thuoc tinh ky thuat cu the cua san pham.")
            lines.append("")
            # Render as-is (may already be markdown table)
            for l in eav_block.strip().splitlines():
                if l.strip():
                    lines.append(l)
            lines.append("")

        if fspaa_block:
            lines.append("### J. FS/PAA Map")
            lines.append("")
            for l in fspaa_block.strip().splitlines():
                if l.strip():
                    lines.append(l)
            lines.append("")

        if src_ctx_block:
            lines.append("### O. Source Context Alignment")
            lines.append("")
            for l in src_ctx_block.strip().splitlines():
                if l.strip():
                    lines.append(l)
            lines.append("")

        section_num += 1

    # ── 1.4 HƯỚNG DẪN VIẾT CHI TIẾT TỪNG H2 ──
    if micro_data:
        lines.append(f"## {section_num}. Hướng Dẫn Viết Chi Tiết")
        lines.append("")
        lines.append("> Mỗi H2 được hướng dẫn cụ thể: Snippet → Phân tích → Information Gain → Bridge")
        lines.append("")

        for i, micro in enumerate(micro_data):
            h2_title = micro.get("h2", "Heading H2")
            intent_tag = micro.get("intent", "")
            is_sapo = (i == 0 and ("sapo" in h2_title.lower() or "mở đầu" in h2_title.lower()))

            if is_sapo:
                lines.append("### 📝 SAPO (Đoạn mở đầu)")
            else:
                lines.append(f"### {h2_title}")

            if intent_tag:
                lines.append(f"*Intent: {intent_tag}*")
            lines.append("")
            
            # V19: Tích hợp 8 thành phần Koray (Agent 4) trực tiếp vào H2 này
            ctx_v4 = brief.get("contextual_structure_v4", {})
            per_h2_dict = ctx_v4.get("per_h2", {}) if isinstance(ctx_v4, dict) else {}
            if isinstance(per_h2_dict, list):
                per_h2_dict = {item.get("h2", "Heading"): item for item in per_h2_dict if isinstance(item, dict)}

            # ── Dynamic project context ──
            project_ctx = brief.get("_project_context")
            brand_name = ""
            brand_lower = ""
            # Phase 37 fix: handle both object (Project dataclass) and dict
            if project_ctx:
                if hasattr(project_ctx, "brand_name"):
                    # Project dataclass object
                    brand_name = getattr(project_ctx, "brand_name", "")
                    brand_lower = brand_name.lower()
                elif isinstance(project_ctx, dict):
                    # Dict format fallback
                    brand_name = project_ctx.get("brand_name", "")
                    brand_lower = brand_name.lower()
            # Build dynamic brand keywords (lowercase + partial matches)
            brand_keywords_main = []
            if brand_lower:
                brand_keywords_main = [
                    brand_lower,
                    brand_lower.replace(" ", ""),
                ]
            brand_keywords_main += [
                "với kinh nghiệm", "chuyên", "phân phối", "cung cấp", "tại miền",
                "biên soạn", "đơn vị chuyên", "hotline", "liên hệ",
            ]

            clean_h2_title = h2_title.replace("[MAIN] ", "").replace("[SUPP] ", "").strip()
            h2_inst = None
            for key, val in per_h2_dict.items():
                # Phase 37: First H2 of the article renders macro_rules block once
                if i == 0:
                    macro_rules = ctx_v4.get("macro_rules", {}) if isinstance(ctx_v4, dict) else {}
                    if macro_rules:
                        lines.append("")
                        lines.append("> **Koray Macro Rules (Toàn Bài):**")
                        if macro_rules.get("central_entity_term"):
                            lines.append(f"> - **Central Entity:** {macro_rules['central_entity_term']}")
                        if macro_rules.get("predicate_cluster"):
                            pc = macro_rules["predicate_cluster"]
                            if isinstance(pc, list): pc = ", ".join(pc)
                            lines.append(f"> - **Predicate Cluster:** {pc}")
                        if macro_rules.get("tonality"):
                            lines.append(f"> - **Tonality:** {macro_rules['tonality']}")
                        lines.append("")
                if clean_h2_title in key or key in clean_h2_title:
                    h2_inst = val
                    break

            # ── Koray Contextual Structure (h2_inst from Agent 4) ──
            is_main = "[MAIN]" in h2_title
            if h2_inst:
                lines.append("> 🎯 **Koray Contextual Structure (Khung bài viết):**")
                if h2_inst.get("content_format"):
                    lines.append(f"> - **Format:** {h2_inst['content_format']}")
                fs = h2_inst.get("first_sentence") or h2_inst.get("first_sentence_pattern", "")
                if fs:
                    lines.append(f"> - **First Sentence:** {fs}")
                # Agent 4 micro_terms: per-H2 specific terms
                mt = h2_inst.get("micro_terms") or h2_inst.get("micro_context_terms", [])
                if mt:
                    if isinstance(mt, list):
                        mt = ", ".join(mt)
                    lines.append(f"> - **Micro Terms:** {mt}")
                # Agent 3 entities as Micro Terms fallback (unique per H2)
                elif micro.get("entities"):
                    ent_str = micro.get("entities", "")
                    # Take only first 5 unique terms for micro_terms display
                    ents = [e.strip() for e in ent_str.replace(",", ";").split(";") if e.strip()][:5]
                    if ents:
                        mt_str = ", ".join(ents)
                        lines.append(f"> - **Micro Terms:** {mt_str}")
                        if len(ents) < 2:
                            lines.append(f"> ⚠️ Micro Terms yếu — cần thêm terms cụ thể hơn cho H2 này")
                # Phase 37: Koray Component ④ — Sentence Before List/Table
                if h2_inst.get("sentence_before"):
                    lines.append(f"> - **Sentence Before:** {h2_inst['sentence_before']}")
                if h2_inst.get("preceding_question"):
                    lines.append(f"> - **Preceding Question:** {h2_inst['preceding_question']}")
                bridge = h2_inst.get("contextual_bridge", "")
                if is_main and any(bk in bridge.lower() for bk in brand_keywords_main):
                    lines.append(f"> ⚠️ **LỖI KORAY:** Brand/hotline trong [MAIN] bridge — chỉ được phép trong [SUPP]")
                if bridge:
                    lines.append(f"> - **Bridge:** {bridge}")
                if h2_inst.get("boolean_h3"):
                    lines.append(f"> - **Boolean H3:** {h2_inst['boolean_h3']}")
                if h2_inst.get("tonality"):
                    lines.append(f"> - **Tonality:** {h2_inst['tonality']}")
                if h2_inst.get("word_count_target"):
                    lines.append(f"> - **Khối lượng:** {h2_inst['word_count_target']}")
                lines.append("")

            # ── Koray Enforcement Layer: Featured Snippet ≤40 words ──
            if micro.get("snippet"):
                raw_snippet = micro["snippet"]
                word_count = len(raw_snippet.split())
                is_over = word_count > 40

                if is_sapo:
                    # ── Koray SAPO: split into Definition + Brand + H2 List ──
                    # Brand keywords that indicate Source Context insertion
                    brand_keywords = ["thép trần long", "tran long", "với kinh nghiệm",
                                      "chuyên", "phân phối", "cung cấp", "tại miền",
                                      "biên soạn", "đơn vị chuyên"]
                    words = raw_snippet.split()

                    # ── Split SAPO into 3 parts ──
                    definition_words = []
                    brand_words = []
                    h2_list_words = []
                    phase = "definition"  # "definition" → "brand" → "h2_list"

                    for w in words:
                        w_lower = w.lower().rstrip(".,;:")
                        # Phase transition: definition → brand
                        if phase == "definition" and any(bk in w_lower for bk in brand_keywords):
                            phase = "brand"
                        # Phase transition: brand → h2_list
                        if phase in ("definition", "brand") and any(m in w_lower for m in ["lần lượt", "bao gồm:", "gồm:"]):
                            phase = "h2_list"

                        if phase == "definition":
                            definition_words.append(w)
                        elif phase == "brand":
                            brand_words.append(w)
                        else:  # h2_list
                            h2_list_words.append(w)

                    definition_text = " ".join(definition_words)
                    brand_text = " ".join(brand_words)
                    h2_list_text = " ".join(h2_list_words)

                    # ── A. Featured Snippet (Definition) — Koray-compliant ≤40 words ──
                    fs_count = len(definition_text.split())
                    lines.append("**A. Featured Snippet — Câu trả lời định nghĩa (≤40 từ):**")
                    lines.append(definition_text)
                    lines.append("")
                    if fs_count <= 40:
                        lines.append(f"> ✅ FS Definition: {fs_count} từ (Koray-compliant)")
                    else:
                        fs_trunc = " ".join(definition_text.split()[:40])
                        lines.append(f"> ⚠️ **LỖI KORAY:** FS Definition {fs_count} từ (vượt ≤40). Rút gọn:")
                        lines.append(f"> {fs_trunc}...")
                    lines.append("")

                    # ── B. Brand (Source Context) — Koray: brand ONLY in [SUPP]/bridge ──
                    _proj = brief.get("_project_context")
                    _brand = getattr(_proj, "brand_name", "") if _proj else "Doanh nghiệp"
                    if brand_text.strip():
                        lines.append(f"**B. Brand — Nguồn gốc & Chuyên môn ({_brand}):**")
                        lines.append(brand_text.strip().rstrip("."))
                        lines.append("")
                        lines.append(f"> 🔗 Koray: Brand chỉ xuất hiện trong [SUPP] hoặc cuối bridge, KHÔNG trong FS Block")
                    else:
                        lines.append(f"**B. Brand — Nguồn gốc & Chuyên môn ({_brand}):**")
                        lines.append("[Tự động sinh khi có EAV Table — LLM ghi nhận thông tin thương hiệu]")
                        lines.append("")

                    # ── C. H2 Roadmap ──
                    if h2_list_text.strip():
                        lines.append("**C. Roadmap bài viết (Các H2 chính):**")
                        lines.append(h2_list_text.strip())
                        lines.append("")
                else:
                    # Regular H2: Featured Snippet ≤40 words
                    lines.append("**A. Featured Snippet (≤40 từ):**")
                    lines.append(raw_snippet)
                    lines.append("")
                    if is_over:
                        fs_trunc = " ".join(raw_snippet.split()[:40])
                        lines.append(f"> ⚠️ **LỖI KORAY:** Snippet {word_count} từ (vượt ≤40). Rút gọn:")
                        lines.append(f"> {fs_trunc}...")
                    else:
                        lines.append(f"> ✅ FS {word_count} từ (Koray-compliant)")
                    lines.append("")

            if micro.get("entities"):
                lines.append(f"**Entities:** {micro['entities']}")
                lines.append("")

            if micro.get("analysis"):
                lines.append(f"**B. Nội dung phân tích chi tiết:** {micro['analysis']}")
                lines.append("")

            if micro.get("info_gain"):
                import re as _re
                info_clean = _re.sub(r'(?i)Các H3 trong phần này bao gồm:.*$', '', micro['info_gain']).strip()
                if info_clean:
                    lines.append(f"**C. Điểm khác biệt & góc nhìn vượt trội:** {info_clean}")
                    lines.append("")

            if micro.get("bridge"):
                # V16 Universal: Dynamic brand name from project context
                _proj = brief.get("_project_context")
                _brand = getattr(_proj, "brand_name", "") if _proj else ""
                _label = f"**D. Liên hệ Source Context ({_brand}):**" if _brand else "**D. Liên hệ Source Context:**"
                lines.append(f"{_label} {micro['bridge']}")
                lines.append("")

            if micro.get("transition"):
                lines.append(f"**E. Câu nối chuyển ý:** *{micro['transition']}*")
                lines.append("")

            lines.append("---")
            lines.append("")

        section_num += 1
    else:
        # Fallback: render raw heading structure
        lines.append(f"## {section_num}. Heading Structure (Raw)")
        lines.append("")
        lines.append("```")
        for heading in heading_structure:
            level = heading["level"]
            text = heading["text"]
            indent = "  " * (int(level[1]) - 1)
            lines.append(f"{indent}{level}: {text}")
        lines.append("```")
        lines.append("")
        section_num += 1

    # ── 1.3 INTERNAL LINKING SUGGESTIONS ──
    lines.append(f"## {section_num}. Internal Linking Suggestions")
    lines.append("")
    lines.append("> 🚨 **QUY TẮC QUAN TRỌNG:** TUYỆT ĐỐI KHÔNG chèn Internal Link vào 9-10 Heading đầu tiên (Khu vực [MAIN] Content). Chỉ chèn link ở khu vực [SUPP] Content hoặc phần cuối bài.")
    lines.append("")

    if "internal_linking" in brief and isinstance(brief["internal_linking"], dict) and "role" in brief["internal_linking"]:
        link_data = brief["internal_linking"]
        mode_label = "(Dynamic từ H2)" if link_data.get("mode") == "dynamic" else "(từ Topical Map)"
        lines.append(f"**Cluster:** {link_data.get('cluster', '?')} | **Role:** {link_data.get('role', '?')} {mode_label}")
        lines.append("")

        tree = link_data.get("tree_view", [])
        if tree:
            lines.append("### Cluster Structure (Cây liên kết)")
            lines.append("")
            lines.append("```")
            for tree_line in tree:
                lines.append(tree_line)
            lines.append("```")
            lines.append("")

        outbound_nodes = link_data.get("outbound_nodes", [])
        if outbound_nodes:
            lines.append("### Trỏ liên kết đến (Outbound → Node con)")
            lines.append("")
            lines.append("| Bài Node | Anchor Text | Các biến thể Anchor |")
            lines.append("|---|---|---|")
            for node in outbound_nodes:
                anchors = node.get("all_anchors", {})
                primary = node.get('anchor', '')
                exact = anchors.get("exact", "")
                semantic = anchors.get("semantic", "")
                question = anchors.get("question", "")
                lines.append(f"| {node.get('topic', '')} | **{primary}** | Exact: \"{exact}\" <br> Semantic: \"{semantic}\" <br> Question: \"{question}\" |")
            lines.append("")

        inbound = link_data.get("inbound_topics", link_data.get("inbound", []))
        if inbound:
            lines.append("### Nhận liên kết từ (Inbound ← Node con)")
            lines.append("")
            if isinstance(inbound, list) and inbound and isinstance(inbound[0], dict):
                for item in inbound:
                    lines.append(f"- [ ] `{item.get('topic', '')}` → trỏ về bài này với anchor: \"{item.get('suggested_anchor', '')}\"")
            else:
                for item in inbound:
                    lines.append(f"- [ ] `{item}`")
            lines.append("")
    elif brief.get("internal_linking") and isinstance(brief["internal_linking"], list):
        lines.append("| Bài viết liên quan | Anchor Text | Vị trí |")
        lines.append("|---|---|---|")
        for link in brief["internal_linking"]:
            if isinstance(link, dict):
                lines.append(f"| {link.get('target_topic', '')} | {link.get('anchor_text_suggestion', '')} | {link.get('placement', '')} |")
        lines.append("")
    else:
        lines.append("> Bật `--linking` để tự động đề xuất Internal Links từ Topical Map.")
        lines.append("")
    section_num += 1

    # ── V11-R3: DEEP CONTEXTUAL INSTRUCTIONS MACRO RULES ──
    ctx_v4 = brief.get("contextual_structure_v4", {})
    macro = ctx_v4.get("macro_rules", {}) if isinstance(ctx_v4, dict) else {}
    if macro:
        lines.append(f"## {section_num}. Deep Contextual Macro Rules")
        lines.append("")
        lines.append("**📌 Macro Rules (Toàn Bài)**")
        lines.append("")
        if macro.get("central_entity_term"):
            lines.append(f"- **Central Entity:** {macro['central_entity_term']}")
        if macro.get("predicate_cluster"):
            pc = macro["predicate_cluster"]
            if isinstance(pc, list):
                pc = ", ".join(pc)
            lines.append(f"- **Predicate Cluster:** {pc}")
        if macro.get("tonality"):
            lines.append(f"- **Tonality:** {macro['tonality']}")
        lines.append("")
        section_num += 1

    # ── V11-S3: TOPICAL MAP POSITION ──
    import csv as _csv
    _base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    _topics_path = None
    # Ưu tiên: project-specific topical_map_csv
    _project_ctx = brief.get("_project_context")
    if _project_ctx and isinstance(_project_ctx, dict):
        _proj_csv = _project_ctx.get("topical_map_csv", "")
        if _proj_csv and os.path.exists(_proj_csv):
            _topics_path = _proj_csv
    # Fallback: global topics.csv
    if not _topics_path:
        _fallback = os.path.join(_base_dir, "topics.csv")
        if os.path.exists(_fallback):
            _topics_path = _fallback
    if _topics_path:
        try:
            _all_topics = []
            with open(_topics_path, mode="r", encoding="utf-8") as _f:
                _reader = _csv.reader(_f)
                _ = next(_reader, None)  # skip header
                for _row in _reader:
                    if _row and _row[0].strip():
                        _all_topics.append(_row[0].strip())

            if _all_topics:
                lines.append(f"## {section_num}. Vị Trí Trong Topical Map")
                lines.append("")
                lines.append(f"> Tổng cộng **{len(_all_topics)} bài viết** trong Topical Map hiện tại.")
                lines.append("")
                # Tìm vị trí bài hiện tại
                current = brief.get("topic", "")
                current_idx = None
                for ci, ct in enumerate(_all_topics):
                    if ct.lower().strip() == current.lower().strip():
                        current_idx = ci
                        break

                lines.append("| # | Keyword | Trạng thái |")
                lines.append("|---|---|---|")
                for ti, t_topic in enumerate(_all_topics):
                    if ti == current_idx:
                        lines.append(f"| {ti+1} | **→ {t_topic}** | 📝 Đang viết |")
                    else:
                        lines.append(f"| {ti+1} | {t_topic} | ⬜ |")
                lines.append("")

                # Check cannibalization
                if current:
                    current_words = set(current.lower().split())
                    for ti, t in enumerate(_all_topics):
                        if t.lower().strip() == current.lower().strip():
                            continue
                        t_words = set(t.lower().split())
                        union = current_words | t_words
                        jaccard = len(current_words & t_words) / len(union) if union else 0
                        if jaccard > 0.6:
                            lines.append(f"> ⚠️ **CẢNH BÁO CANNIBALIZATION:** Bài viết [{t}] có độ trùng lặp Jaccard={jaccard:.2f}. Cần gom nhóm (merge) hoặc phân tách intent rõ ràng.")
                            lines.append("")
                section_num += 1
        except Exception as _map_err:
            logger.warning("  [EXPORTER] Topical map render failed: %s", _map_err)
            lines.append("> ⚠️ Không thể render Topical Map. Kiểm tra file topics.csv.")
            lines.append("")

    # ── V11-S1: GEO / AI OVERVIEW OPTIMIZATION ──
    try:
        from modules.geo_schema_generator import generate_geo_schemas
        # Lấy project từ brief nếu có
        _project = brief.get("_project_context", None)
        geo_md = generate_geo_schemas(brief, _project)
        if geo_md:
            lines.append(f"## {section_num}. {geo_md.split(chr(10))[0].replace('## ', '')}")
            lines.append("")
            # Render phần còn lại (bỏ dòng đầu)
            for geo_line in geo_md.split("\n")[1:]:
                lines.append(geo_line)
            section_num += 1
    except Exception as _geo_err:
        logger.warning("  [EXPORTER] GEO schema generation failed: %s", _geo_err)

    # ── 1.4 PROMPT DÀNH CHO AI WRITER ──
    lines.append(f"## {section_num}. Prompt Dành Cho AI Writer (Hướng dẫn đọc Brief)")
    lines.append("")
    lines.append("> 🤖 **COPY TOÀN BỘ TEXT DƯỚI ĐÂY KÈM THEO DÀN Ý ĐỂ ĐƯA VÀO CHATGPT/CLAUDE:**")
    lines.append("")
    lines.append("```text")
    lines.append("Nhiệm vụ của bạn là đóng vai một chuyên gia Content Writer SEO cấp cao, am hiểu sâu sắc về Semantic SEO.")
    lines.append("Hãy viết MỘT BÀI VIẾT HOÀN CHỈNH bám sát cấu trúc Dàn ý chi tiết (Semantic Outline) mà tôi cung cấp ở trên.")
    lines.append("")
    lines.append("QUY TẮC BẮT BUỘC (MUST FOLLOW):")
    lines.append("1. TỔNG HỢP LOGIC, KHÔNG COPY NHÃN: Dưới mỗi Heading (H2/H3), dàn ý được chi nhỏ thành các khối thông tin (A. Snippet, B. Nội dung phân tích, C. Information Gain, D. Contextual Bridge). Tuyệt đối KHÔNG in ra các ký tự A, B, C, D vào bài viết! Hãy hòa trộn các khối thông tin đó thành một khối văn bản mượt mà, chuyên nghiệp.")
    lines.append("2. Lồng ghép các từ khóa ngữ nghĩa (Entities) được yêu cầu một cách tự nhiên nhất.")
    lines.append("3. Giữ MỌI bảng biểu (Information Gain/Bảng so sánh) và xuất chính xác các số liệu kỹ thuật/EAV Table đã được cung cấp sẵn.")
    lines.append("4. Tại các mục [SUPP] (Supplement Content) hoặc đoạn chuyển ý cuối cùng, BẮT BUỘC chèn thông tin Brand/Hotline/CTA và các Gợi ý Internal Link đúng với Anchor text đã cấp.")
    lines.append("5. Tuyệt đối không tự ý đẻ thêm Heading H2/H3 ngoài dàn ý. Hãy Viết dài, viết sâu, và bám sát Methodology (Phong cách viết).")
    lines.append("```")
    lines.append("")

    # ══════════════════════════════════════════════════════════
    #  PHẦN 2: BÁO CÁO PHÂN TÍCH DỮ LIỆU & CHIẾN LƯỢC (PART 2)
    # ══════════════════════════════════════════════════════════
    lines.append("---")
    lines.append("")
    lines.append("# PHẦN 2: METHODOLOGY & WRITING GUIDELINES")  # Giữ text này để split ở cuối hàm
    lines.append(f"# BÁO CÁO PHÂN TÍCH: {brief['topic']}")
    lines.append("")
    
    # ── 2.1 TRỤC CHIẾN LƯỢC (Core Strategy) ──
    lines.append("## 1. Trục Chiến Lược (Core Strategy)")
    lines.append("")
    intent_info = brief.get("search_intent", {})
    if isinstance(intent_info, dict):
        lines.append(f"- **Search Intent**: {intent_info.get('type', 'N/A')} — {intent_info.get('description', '')}")
    else:
        lines.append("- **Search Intent**: N/A")
        
    lines.append(f"- **Methodology**: {brief.get('methodology_prompt', 'General').split('.')[0] if brief.get('methodology_prompt') else 'General'}")
    
    # Main/Supp Split & H3 Ratio summary
    main_h = [h for h in heading_structure if "[MAIN]" in h.get("text", "")]
    supp_h = [h for h in heading_structure if "[SUPP]" in h.get("text", "")]
    main_total = len(main_h)
    supp_total = len(supp_h)
    total = main_total + supp_total
    pct = round(supp_total / total * 100) if total > 0 else 0
    lines.append(f"- **Cấu trúc**: {total} H2 ({pct}% là Supplement Content). {h3_count} H3 (Ratio: {ratio_pct}%).")
    lines.append("")

    # ── 2.2 DỮ LIỆU SERP TỎNG QUAN ──
    lines.append("## 2. Dữ liệu SERP & Đối Thủ")
    lines.append("")
    
    if has_serp and has_competitor:
        serp = brief["serp_analysis"]
        comp = brief["competitor_analysis"]
        
        # Bảng đối thủ
        if comp.get("competitors_summary"):
            lines.append("### Top 5 Đối thủ phân tích")
            lines.append("| # | URL | Headings | Words |")
            lines.append("|---|---|---|---|")
            for i, c in enumerate(comp["competitors_summary"][:5], 1):
                url_short = c["url"][:60] + "..." if len(c["url"]) > 60 else c["url"]
                lines.append(f"| {i} | {url_short} | {c.get('heading_count', 0)} | {c.get('word_count', 0):,} |")
            lines.append("")

        # PAA & Entities (2 columns representation using lists)
        lines.append("### Khai thác & Mở rộng")
        if serp.get("people_also_ask"):
            lines.append("**Top PAA (People Also Ask):**")
            for q in serp["people_also_ask"][:5]:
                lines.append(f"- {q}")
            lines.append("")
            
        info_gain = comp.get("information_gain", {})
        if info_gain.get("rare_headings"):
            lines.append("**Semantic Voids (Rare Headings):**")
            for h in info_gain["rare_headings"][:5]:
                lines.append(f"- {h}")
            lines.append("")
    else:
        lines.append("> ⚠️ KHÔNG CÓ DỮ LIỆU CRAWL SERP/COMPETITOR.\n")

    # ── 2.3 SEMANTIC KEYWORD NETWORK ──
    lines.append("## 3. Semantic Keyword Network (Clusters)")
    lines.append("")
    if "query_network" in brief:
        net = brief["query_network"]
        lines.append(f"*(Từ {net.get('total_fetched', 0)} keyword ban đầu → {net.get('clustered_kws_count', 0)} keyword cốt lõi)*\n")
        clusters_data = net.get("clusters", {})
        if "error" in clusters_data:
            lines.append(f"**Lỗi**: {clusters_data['error']}\n")
        else:
            for c in clusters_data.get("clusters", [])[:6]:  # Show top 6 clusters
                kws = ", ".join(c.get('keywords', [])[:4])
                lines.append(f"- **{c.get('cluster_name', 'Unnamed')}** ({c.get('intent', 'N/A')}): {kws}")
            lines.append("")
    else:
        lines.append("> (Không có dữ liệu Network)\n")

    # ── 2.4 E-E-A-T & QUALITY CHECKS ──
    lines.append("## 4. E-E-A-T & Quality Checks")
    lines.append("")
    
    if "source_context_alignment" in brief:
        lines.append("**Source Context Alignment (Độ khớp với website):**")
        lines.append(brief["source_context_alignment"])
        lines.append("")

    eeat = brief.get("eeat_checklist", [])
    if eeat:
        lines.append("**E-E-A-T Tasks:**")
        # Check if it's the old dict format or the new string list
        if isinstance(eeat[0], dict):
            for item in eeat[:4]:
                lines.append(f"- [ ] **{item.get('criterion', '')}**: {item.get('action', '')}")
        else:
            for item in eeat[:4]:
                lines.append(f"- [ ] {item}")
        lines.append("")
        
    guidelines = brief.get("content_guidelines", [])
    if guidelines:
        lines.append("**Nguyên tắc viết SEO:**")
        if isinstance(guidelines[0], dict):
            for guideline in guidelines[:3]:
                lines.append(f"- {guideline.get('section', '')}: {guideline.get('word_count', '')} từ ({guideline.get('guideline', '')})")
        else:
            for guideline in guidelines[:3]:
                lines.append(f"- {guideline}")
        lines.append("")

    # ── FOOTER ──
    lines.append("---")
    lines.append("")
    lines.append("*Báo cáo tự động từ Content Brief Generator Pipeline (V8.1)*")

    full_content = "\n".join(lines)
    
    # Simple split for part1 and part2
    parts = full_content.split("# PHẦN 2: METHODOLOGY & WRITING GUIDELINES")
    part1_md = parts[0] if len(parts) > 0 else full_content
    part2_md = "# PHẦN 2: METHODOLOGY & WRITING GUIDELINES" + parts[1] if len(parts) > 1 else ""

    return full_content, part1_md, part2_md
