
file_path = r"d:\antigravity\content brief\modules\markdown_exporter.py"

with open(file_path, "r", encoding="utf-8") as f:
    original_code = f.read()

new_function = """def _render_markdown(brief: Dict) -> Tuple[str, str, str]:
    \"\"\"
    Render toàn bộ Content Brief thành chuỗi Markdown.

    Cấu trúc "Show Your Work" (V7):
        PHẦN 1: ACTIONABLE CONTENT BRIEF
        PHẦN 2: METHODOLOGY & WRITING GUIDELINES
        PHẦN 3: DATA ANALYSIS (Reference)
        
    Returns:
        Tuple[str, str, str]: (full_content, part1_content, part2_content)
    \"\"\"
    lines = []
    
    # ── HEADER ──
    lines.append(f"# BÁO CÁO PHÂN TÍCH & CONTENT BRIEF: {brief['topic']}")
    lines.append("")
    lines.append("> **Ngày tạo**: Auto-generated by Content Brief Generator")
    lines.append("")
    lines.append("---")
    lines.append("")

    has_serp = "serp_analysis" in brief
    has_competitor = "competitor_analysis" in brief

    # ══════════════════════════════════════════════════════════
    #  PHẦN 1: ACTIONABLE CONTENT BRIEF
    # ══════════════════════════════════════════════════════════
    lines.append("# PHẦN 1: ACTIONABLE CONTENT BRIEF")
    lines.append("")
    
    section_num = 1
    
    # ── 1.1 META INFORMATION ──
    lines.append(f"## {section_num}. Meta Information")
    lines.append("")
    lines.append("| Hạng mục | Nội dung |")
    lines.append("|---|---|")
    lines.append(f"| **Title Tag** | {brief.get('title_tag', '')} |")
    lines.append(f"| **Meta Description** | {brief.get('meta_description', '')} |")
    lines.append(f"| **Target Keyword** | {brief['topic']} |")
    lines.append(f"| **Central Entity** | {brief.get('central_entity', '')} |")
    lines.append("")
    section_num += 1

    # ── 1.2 SEMANTIC OUTLINE (DÀN Ý CHI TIẾT) ──
    lines.append(f"## {section_num}. Semantic Outline (Dàn ý chi tiết A-B-C-D-E)")
    lines.append("")
    
    if has_serp and has_competitor:
        lines.append("> ✅ Outline được xây dựng từ dữ liệu thực tế (PAA + Competitor Headings + Content Gaps)")
    else:
        lines.append("> ⚠️ Outline là template rule-based (không có dữ liệu SERP)")
    lines.append("")

    micro_data = brief.get("micro_briefing", [])
    heading_structure = brief.get("heading_structure", [])

    if micro_data:
        # Build a map from H2 -> list of H3s
        h3s_by_h2 = {}
        current_h2_text = ""
        for h in heading_structure:
            text = h["text"]
            lvl = h["level"]
            if lvl == "H2":
                current_h2_text = text
                h3s_by_h2[current_h2_text] = []
            elif lvl == "H3" and current_h2_text:
                h3s_by_h2[current_h2_text].append(text)

        for i, micro in enumerate(micro_data):
            h2_title = micro.get("h2", "Heading H2")
            intent_tag = micro.get("intent", "")

            is_sapo = (i == 0 and ("sapo" in h2_title.lower() or "mở đầu" in h2_title.lower()))

            if is_sapo:
                lines.append("### SAPO (Đoạn mở đầu)")
                if intent_tag:
                    lines.append(f"*(Vai trò: {intent_tag})*")
                lines.append("")
            else:
                prefix = "H2: " if not h2_title.upper().startswith("H") else ""
                lines.append(f"### {prefix}{h2_title}")
                if intent_tag:
                    lines.append(f"*(Intent: {intent_tag})*")
                lines.append("")

            # Find H3s for this H2
            matching_h3s = []
            for h2_key, h3_list in h3s_by_h2.items():
                clean_key = h2_key.replace("[MAIN]", "").replace("[SUPP]", "").strip()
                clean_title = h2_title.replace("[MAIN]", "").replace("[SUPP]", "").strip()
                if clean_title in clean_key or clean_key in clean_title:
                    matching_h3s = h3_list
                    break

            if micro.get("snippet"):
                label_a = "**Nội dung SAPO (80-120 từ):**" if is_sapo else "**A. Câu trả lời trực diện (Snippet Block):**"
                lines.append(label_a)
                lines.append(f"{micro['snippet']}")
                lines.append("")

            if matching_h3s and not is_sapo:
                lines.append("**📍 CÁC TIÊU ĐỀ CON (H3) TRONG PHẦN NÀY:**")
                for h3 in matching_h3s:
                    lines.append(f"- **H3:** {h3}")
                lines.append("")

            if micro.get("analysis"):
                lines.append("**B. Nội dung phân tích & Công thức chuyên sâu:**")
                lines.append(f"{micro['analysis']}")
                lines.append("")

            if micro.get("entities"):
                lines.append(f"**Entities:** {micro['entities']}")
                lines.append("")

            if micro.get("info_gain"):
                import re
                info_gain_clean = re.sub(r'(?i)Các H3 trong phần này bao gồm:.*$', '', micro['info_gain']).strip()
                if info_gain_clean:
                    lines.append("**C. Điểm khác biệt & Góc nhìn vượt trội (Information Gain):**")
                    lines.append(f"{info_gain_clean}")
                    lines.append("")

            if micro.get("bridge"):
                lines.append("**D. Hướng dẫn áp dụng giải pháp (Contextual Bridge):**")
                lines.append(f"{micro['bridge']}")
                lines.append("")

            if micro.get("transition"):
                lines.append("**E. Câu nối chuyển ý:**")
                lines.append(f"{micro['transition']}")
                lines.append("")

            lines.append("---")
            lines.append("")
    else:
        lines.append("```")
        for heading in brief["heading_structure"]:
            level = heading["level"]
            text = heading["text"]
            indent = "  " * (int(level[1]) - 1)
            lines.append(f"{indent}{level}: {text}")
        lines.append("```")
        lines.append("")
    section_num += 1

    # ── 1.3 INTERNAL LINKING SUGGESTIONS ──
    lines.append(f"## {section_num}. Internal Linking Suggestions")
    lines.append("")
    lines.append("> 🚨 **QUY TẮC QUAN TRỌNG:** TUYỆT ĐỐI KHÔNG chèn Internal Link vào 9-10 Heading đầu tiên (Khu vực [MAIN] Content). Chỉ chèn link ở khu vực [SUPP] Content hoặc phần cuối bài.")
    lines.append("")

    if "internal_linking" in brief and isinstance(brief["internal_linking"], dict) and "role" in brief["internal_linking"]:
        link_data = brief["internal_linking"]
        mode_label = "(Dynamic từ H2)" if link_data.get("mode") == "dynamic" else "(từ Topical Map)"
        lines.append(f"**Cluster:** {link_data.get('cluster', '?')} | **Role:** {link_data.get('role', '?')} {mode_label}")
        lines.append("")

        tree = link_data.get("tree_view", [])
        if tree:
            lines.append("### Cluster Structure (Cây liên kết)")
            lines.append("")
            lines.append("```")
            for tree_line in tree:
                lines.append(tree_line)
            lines.append("```")
            lines.append("")

        outbound_nodes = link_data.get("outbound_nodes", [])
        if outbound_nodes:
            lines.append("### Trỏ liên kết đến (Outbound → Node con)")
            lines.append("")
            lines.append("| Bài Node | Anchor Text | Các biến thể Anchor |")
            lines.append("|---|---|---|")
            for node in outbound_nodes:
                anchors = node.get("all_anchors", {})
                variants = " / ".join([
                    f'"{anchors.get("exact", "")}"',
                    f'"{anchors.get("semantic", "")}"',
                    f'"{anchors.get("question", "")}"',
                ])
                lines.append(f"| {node.get('topic', '')} | **{node.get('anchor', '')}** | {variants} |")
            lines.append("")

        inbound = link_data.get("inbound_topics", link_data.get("inbound", []))
        if inbound:
            lines.append("### Nhận liên kết từ (Inbound ← Node con)")
            lines.append("")
            if isinstance(inbound, list) and inbound and isinstance(inbound[0], dict):
                for item in inbound:
                    lines.append(f"- [ ] `{item.get('topic', '')}` → trỏ về bài này với anchor: \\\"{item.get('suggested_anchor', '')}\\\"")
            else:
                for item in inbound:
                    lines.append(f"- [ ] `{item}`")
            lines.append("")
    elif brief.get("internal_linking") and isinstance(brief["internal_linking"], list):
        lines.append("| Bài viết liên quan | Anchor Text | Vị trí |")
        lines.append("|---|---|---|")
        for link in brief["internal_linking"]:
            if isinstance(link, dict):
                lines.append(f"| {link.get('target_topic', '')} | {link.get('anchor_text_suggestion', '')} | {link.get('placement', '')} |")
        lines.append("")
    else:
        lines.append("> Bật `--linking` để tự động đề xuất Internal Links từ Topical Map.")
        lines.append("")
    section_num += 1

    # ── 1.4 PROMPT DÀNH CHO AI WRITER ──
    lines.append(f"## {section_num}. Prompt Dành Cho AI Writer (Hướng dẫn đọc Brief)")
    lines.append("")
    lines.append("> 🤖 **COPY TOÀN BỘ TEXT DƯỚI ĐÂY KÈM THEO DÀN Ý ĐỂ ĐƯA VÀO CHATGPT/CLAUDE:**")
    lines.append("")
    lines.append("```text")
    lines.append("Nhiệm vụ của bạn là đóng vai một chuyên gia Content Writer SEO cấp cao, am hiểu sâu sắc về Semantic SEO.")
    lines.append("Hãy viết MỘT BÀI VIẾT HOÀN CHỈNH bám sát cấu trúc Dàn ý chi tiết (Semantic Outline) mà tôi cung cấp ở trên.")
    lines.append("")
    lines.append("QUY TẮC BẮT BUỘC (MUST FOLLOW):")
    lines.append("1. TỔNG HỢP LOGIC, KHÔNG COPY NHÃN: Dưới mỗi Heading (H2/H3), dàn ý được chi nhỏ thành các khối thông tin (A. Snippet, B. Nội dung phân tích, C. Information Gain, D. Contextual Bridge). Tuyệt đối KHÔNG in ra các ký tự A, B, C, D vào bài viết! Hãy hòa trộn các khối thông tin đó thành một khối văn bản mượt mà, chuyên nghiệp.")
    lines.append("2. Lồng ghép các từ khóa ngữ nghĩa (Entities) được yêu cầu một cách tự nhiên nhất.")
    lines.append("3. Giữ MỌI bảng biểu (Information Gain/Bảng so sánh) và xuất chính xác các số liệu kỹ thuật/EAV Table đã được cung cấp sẵn.")
    lines.append("4. Tại các mục [SUPP] (Supplement Content) hoặc đoạn chuyển ý cuối cùng, BẮT BUỘC chèn thông tin Brand/Hotline/CTA và các Gợi ý Internal Link đúng với Anchor text đã cấp.")
    lines.append("5. Tuyệt đối không tự ý đẻ thêm Heading H2/H3 ngoài dàn ý. Hãy Viết dài, viết sâu, và bám sát Methodology (Phong cách viết).")
    lines.append("```")
    lines.append("")

    # ══════════════════════════════════════════════════════════
    #  PHẦN 2: METHODOLOGY & WRITING GUIDELINES
    # ══════════════════════════════════════════════════════════
    lines.append("---")
    lines.append("")
    lines.append("# PHẦN 2: METHODOLOGY & WRITING GUIDELINES")
    lines.append("")
    section_num = 1
    
    # ── 2.1 METHODOLOGY ──
    lines.append(f"## {section_num}. Methodology (Phong cách viết)")
    lines.append("")
    lines.append("Tuân thủ nghiêm ngặt các quy tắc viết sau đây:")
    lines.append("")
    if brief.get("methodology_prompt"):
        for line in brief["methodology_prompt"].split("\\n"):
            if line.strip():
                lines.append(f"> {line}")
    else:
        lines.append("> (Sử dụng phong cách viết General)")
    lines.append("")
    section_num += 1

    # ── 2.2 SEARCH INTENT ──
    intent_info = brief.get("search_intent", {})
    if isinstance(intent_info, dict):
        lines.append(f"## {section_num}. Search Intent")
        lines.append("")
        lines.append(f"- **Loại**: {intent_info.get('type', '')}")
        lines.append(f"- **Mô tả**: {intent_info.get('description', '')}")
        lines.append(f"- **Focus nội dung**: {intent_info.get('content_focus', '')}")
        lines.append("")
        section_num += 1

    # ── 2.3 ENTITY ATTRIBUTES ──
    attrs = brief.get("entity_attributes", {})
    if isinstance(attrs, dict) and attrs:
        lines.append(f"## {section_num}. Entity Attributes")
        lines.append("")
        lines.append("### Root Attributes (Thuộc tính gốc)")
        for attr in attrs.get("root_attributes", []):
            lines.append(f"- {attr}")
        lines.append("")
        if attrs.get("rare_attributes") and attrs["rare_attributes"][0] != "Không có thuộc tính hiếm đặc biệt":
            lines.append("### Rare Attributes")
            for attr in attrs["rare_attributes"]:
                lines.append(f"- {attr}")
            lines.append("")
        if attrs.get("unique_attributes") and attrs["unique_attributes"][0] != "Không có thuộc tính độc nhất đặc biệt":
            lines.append("### Unique Attributes")
            for attr in attrs["unique_attributes"]:
                lines.append(f"- {attr}")
            lines.append("")
        section_num += 1

    # ── 2.4 CONTENT GUIDELINES ──
    guidelines = brief.get("content_guidelines", [])
    if isinstance(guidelines, list) and guidelines:
        lines.append(f"## {section_num}. Content Guidelines (Hướng dẫn viết tổng quan)")
        lines.append("")
        for guideline in guidelines:
            lines.append(f"### {guideline.get('section', '')}")
            lines.append(f"- **Số từ**: {guideline.get('word_count', '')}")
            lines.append(f"- **Hướng dẫn**: {guideline.get('guideline', '')}")
            lines.append("")
        section_num += 1

    # ── 2.5 SUGGESTED QUESTIONS (K2Q) ──
    suggested = brief.get("suggested_questions", [])
    if suggested:
        lines.append(f"## {section_num}. Suggested Questions (K2Q)")
        lines.append("")
        for i, question in enumerate(suggested, 1):
            lines.append(f"{i}. {question}")
        lines.append("")
        section_num += 1

    # ── 2.6 E-E-A-T CHECKLIST ──
    eeat = brief.get("eeat_checklist", [])
    if eeat:
        lines.append(f"## {section_num}. E-E-A-T Checklist")
        lines.append("")
        for item in eeat:
            lines.append(f"### {item.get('criterion', '')}")
            lines.append(f"- [ ] {item.get('action', '')}")
            lines.append("")
        section_num += 1
    
    # ── 2.7 SOURCE CONTEXT ALIGNMENT ──
    if "source_context_alignment" in brief:
        lines.append(f"## {section_num}. Source Context Alignment")
        lines.append("")
        lines.append(brief["source_context_alignment"])
        lines.append("")
        section_num += 1

    # ── 2.8 HEADING PRIORITY ──
    lines.append(f"## {section_num}. Heading Priority (Attribute Filtration)")
    lines.append("")
    h2_items = [h for h in heading_structure if h.get("level") == "H2"]
    if h2_items:
        lines.append("| # | H2 Heading | Vai trò | Lý do |")
        lines.append("|---|-----------|---------|-------|")
        for idx, h in enumerate(h2_items, 1):
            text = h.get("text", "")
            role = "[MAIN]" if "[MAIN]" in text else ("[SUPP]" if "[SUPP]" in text else "—")
            clean = text.replace("[MAIN]", "").replace("[SUPP]", "").strip()
            lines.append(f"| {idx} | {clean} | {role} | Vị trí #{idx} theo Contextual Hierarchy |")
        lines.append("")
    else:
        lines.append("_(Không có H2 headings)_")
        lines.append("")
    section_num += 1

    # ── 2.9 MAIN/SUPP CONTENT SPLIT ──
    lines.append(f"## {section_num}. Main/Supp Content Split")
    lines.append("")
    main_h = [h for h in heading_structure if "[MAIN]" in h.get("text", "")]
    supp_h = [h for h in heading_structure if "[SUPP]" in h.get("text", "")]
    main_total = len(main_h)
    supp_total = len(supp_h)
    lines.append(f"- **Main Content**: {main_total} H2 headings — Nội dung cốt lõi, trả lời Search Intent")
    lines.append(f"- **Supplement Content**: {supp_total} H2 headings — FAQ, CTA, brand context, internal links")
    total = main_total + supp_total
    if total > 0:
        pct = round(supp_total / total * 100)
        status = "✅ Đạt chuẩn" if 20 <= pct <= 35 else "⚠️ Cần điều chỉnh"
        lines.append(f"- **Tỉ lệ Supplement**: {pct}% ({status}, chuẩn: 20-35%)")
    lines.append("")
    lines.append("> **Quy tắc:** TUYỆT ĐỐI KHÔNG chèn Internal Link, CTA, Brand Mention vào khu vực [MAIN].")
    lines.append("")
    section_num += 1

    # ══════════════════════════════════════════════════════════
    #  PHẦN 3: DATA ANALYSIS (Reference)
    # ══════════════════════════════════════════════════════════
    lines.append("---")
    lines.append("")
    lines.append("# PHẦN 3: DATA ANALYSIS (Reference)")
    lines.append("")
    section_num = 1

    # ── 3.1 DỮ LIỆU SERP ──
    lines.append(f"## 3.1 Dữ liệu SERP")
    lines.append("")
    if has_serp:
        serp = brief["serp_analysis"]
        top_urls = serp.get("top_urls_display", serp.get("top_urls", []))
        if top_urls:
            lines.append("### Top Đối thủ")
            for i, url in enumerate(top_urls[:10], 1): lines.append(f"{i}. {url}")
            lines.append("")
        if serp.get("people_also_ask"):
            lines.append("### People Also Ask")
            for i, q in enumerate(serp["people_also_ask"], 1): lines.append(f"{i}. {q}")
            lines.append("")
        if serp.get("dominant_intent"):
            lines.append(f"**Dominant Intent:** {serp['dominant_intent']}\\n")
        entities = serp.get("serp_entities", {})
        if entities.get("primary"):
            lines.append("### Thực thể chính:")
            for e in entities["primary"][:10]: lines.append(f"- {e}")
            lines.append("")
        if serp.get("topic_clusters"):
            lines.append("### Topic Clusters")
            for cluster in serp["topic_clusters"][:10]: lines.append(f"- {cluster}")
            lines.append("")
    else:
        lines.append("> ⚠️ KHÔNG CÓ DỮ LIỆU SERP.\\n")

    # ── 3.2 PHÂN TÍCH ĐỐI THỦ ──
    lines.append(f"## 3.2 Phân tích Đối thủ")
    lines.append("")
    if has_competitor:
        comp = brief["competitor_analysis"]
        if comp.get("competitors_summary"):
            lines.append("### Tổng quan đối thủ")
            lines.append("| # | URL | Headings | Words |")
            lines.append("|---|---|---|---|")
            for i, c in enumerate(comp["competitors_summary"], 1):
                url_short = c["url"][:60] + "..." if len(c["url"]) > 60 else c["url"]
                lines.append(f"| {i} | {url_short} | {c.get('heading_count', 0)} | {c.get('word_count', 0):,} |")
            lines.append("")
        if comp.get("common_headings"):
            lines.append("### Common Headings")
            for h in comp["common_headings"][:15]: lines.append(f"- {h}")
            lines.append("")
        if comp.get("ngrams_2"):
            lines.append("### Top 2-grams:")
            lines.append("| Cụm từ | Số đối thủ |")
            lines.append("|---|---|")
            for ng, cnt in comp["ngrams_2"][:15]: lines.append(f"| {ng} | {cnt} |")
            lines.append("")
        info_gain = comp.get("information_gain", {})
        if info_gain.get("rare_headings"):
            lines.append("### Semantic Voids (Rare Headings)")
            for h in info_gain["rare_headings"][:10]: lines.append(f"- {h}")
            lines.append("")
    else:
        lines.append("> ⚠️ KHÔNG CÓ DỮ LIỆU ĐỐI THỦ.\\n")

    # ── 3.3 SEMANTIC KEYWORD NETWORK ──
    lines.append(f"## 3.3 Semantic Keyword Network")
    lines.append("")
    if "query_network" in brief:
        net = brief["query_network"]
        lines.append(f"- Tổng keyword thu thập: {net.get('total_fetched', 0)}")
        lines.append(f"- Số keyword phân cụm: {net.get('clustered_kws_count', 0)}\\n")
        clusters_data = net.get("clusters", {})
        if "error" in clusters_data:
            lines.append(f"**Lỗi**: {clusters_data['error']}\\n")
        else:
            for c in clusters_data.get("clusters", []):
                lines.append(f"### Cluster: {c.get('cluster_name', 'Unnamed')}")
                lines.append(f"- Intent: {c.get('intent', 'N/A')}")
                lines.append(f"- Primary Keyword: **{c.get('primary_keyword', 'N/A')}**\\n")
    
    # ── FOOTER ──
    lines.append("---")
    lines.append("")
    lines.append("*Content Brief được tạo tự động bởi Content Brief Generator Pipeline.*")

    full_content = "\\n".join(lines)
    part1_md = "PART 1 MOCK"
    part2_md = "PART 2 MOCK"

    return full_content, part1_md, part2_md
"""

top_part = original_code[:original_code.find("def _render_markdown")]
new_file_content = top_part + new_function

with open(file_path, "w", encoding="utf-8") as f:
    f.write(new_file_content)

print(f"File {file_path} replaced with new structure.")
